name: Run Python Script Daily

on:
  schedule:
    - cron: '30 0 * * *'  # UTC 기준으로 매일 오후 0시 30분, 한국 시간으로는 오전 9시 30분
    - cron: '0 2 * * *'  # UTC 기준으로 매일 오전 2시 (한국 시간으로 오전 11시)
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium requests

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          if [ ! -f /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

      - name: Run Python script
        run: python ranking.py

      - name: Upload Debug Artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: debug-info
          path: |
            page_source.html
            screenshot.png
